### ISSUE TITLE
Add arguments in the lineGraph() method, _plot module

### ISSUE THREAD

**Issue by vsaveris** [vsaveris/trading-technical-indicators#1]
Add the below arguments in the method, as optional:

- linewidth
- linestyle
- alpha

Each of these should be a list with members equal to the number of the plotted lines. If None is entered for a line then default values apply. If parameters are not present then default values apply to all the lines.

**Comment by sid11k** [comment]
Hi Im trying to work on this but I'm new. I just wanted to clarify -- so each of linewidth, linestyle, and alpha should be a list passed into the lineGraph method? When you say "list with members equal to number of plotted lines," does this mean each argument has "data.index.values" number of members?

**Comment by vsaveris** [comment]
hi @sid11k ,

the lineGraph method creates a plot with lines equal to the **data.shape[1]**. Actually each column of the **`data`** dataframe represents a line in the plot.

So, if for example the dataframe has three columns, the arguments should look like:
- linewitdth = [2.0, 1.5, 2.0]
- linestyle = ['-', '--', '-.']
- alpha = [1.0, 0.5, 0.75]

One entry for each line (where data.shape[1] lines).

For a line the default values can be used by using the `None` keyword. For example:
- linewidth = [None, 0.5, 1.0] , but all these values can be passed safely to the plt.plot(...) call.

Last, I would suggest to follow the example of the colors_palette for handling default values and rotation in the argument's members.

The default values for all the three arguments should be the list **[None]**, considering that a rotation style will be applied like in the colors palette case (**colors_palette[i % len(colors_palette)]**).

Hope it helps. If you need further information, feel free to ask.

**Comment by sid11k** [comment]
Was this commit along the lines you were thinking or no?

**Comment by vsaveris** [comment]
Code tested and merge completed.
